version: '3.4'

networks: 
  makeitsimple.webapi:

services:
  makeitsimple.webapi:
    image: makeitsimplewebapi
    build:
      context: .
      dockerfile: MakeItSimple.WebApi/Dockerfile
    ports:
      - "5000:5000"  
      - "5001:5001" 
    environment:
      - ConnectionStrings__Testing=Data Source=97.74.81.27; Initial Catalog=misdb_pretest;User ID=sa; Password=r30JNfwv1@Vbb$gq; Connect Timeout=600;Encrypt=False; Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False;Pooling=false
    networks: 
      - makeitsimple.webapi
    depends_on: 
      - mis.database

  mis.database: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mis.database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=r30JNfwv1@Vbb$gq
    ports:
      - "1433:1433"
    networks:
      - makeitsimple.webapi

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    networks:
      - makeitsimple.webapi
